"""adding loan details model

Revision ID: 1789560d2ecb
Revises: d25a8a8cfbc3
Create Date: 2025-02-01 19:50:48.757527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1789560d2ecb'
down_revision = 'd25a8a8cfbc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LoanDetails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('principal', sa.Float(), nullable=False),
    sa.Column('annual_interest_rate', sa.Float(), nullable=False),
    sa.Column('term_years', sa.Integer(), nullable=False),
    sa.Column('payment_frequency', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LoanDetails_id'), 'LoanDetails', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LoanDetails_id'), table_name='LoanDetails')
    op.drop_table('LoanDetails')
    # ### end Alembic commands ###
