"""Added new field to users_info

Revision ID: 2c7dbf238fbe
Revises: 1789560d2ecb
Create Date: 2025-02-16 11:44:01.249925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c7dbf238fbe'
down_revision = '1789560d2ecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    
    op.add_column('users_info', sa.Column('role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###
