"""overhauling tables

Revision ID: 600ce23d9979
Revises: 2c7dbf238fbe
Create Date: 2025-02-16 13:44:36.798910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '600ce23d9979'
down_revision = '2c7dbf238fbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('othernames', sa.String(length=255), nullable=False),
    sa.Column('residential_address', sa.String(length=255), nullable=True),
    sa.Column('postal_address', sa.String(length=255), nullable=True),
    sa.Column('client_phone_no', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('employer', sa.String(length=255), nullable=True),
    sa.Column('previous_employee_no', sa.String(length=100), nullable=True),
    sa.Column('social_security_no', sa.String(length=100), nullable=True),
    sa.Column('voters_id_no', sa.String(length=100), nullable=True),
    sa.Column('employment_date', sa.Date(), nullable=True),
    sa.Column('next_of_kin', sa.String(length=255), nullable=True),
    sa.Column('next_of_kin_contact', sa.String(length=50), nullable=True),
    sa.Column('next_of_kin_address', sa.String(length=255), nullable=True),
    sa.Column('search_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', 'employee_id')
    )
    op.create_index(op.f('ix_individual_clients_employee_id'), 'individual_clients', ['employee_id'], unique=False)
    op.create_index(op.f('ix_individual_clients_search_name'), 'individual_clients', ['search_name'], unique=False)
    op.create_table('macros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employment_rate', sa.Float(), nullable=False),
    sa.Column('inflation_rate', sa.Float(), nullable=False),
    sa.Column('gdp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_security',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_fk', sa.Integer(), nullable=False),
    sa.Column('collateral_description', sa.String(length=255), nullable=False),
    sa.Column('collateral_value', sa.Float(), nullable=False),
    sa.Column('forced_sale_value', sa.Float(), nullable=False),
    sa.Column('method_of_valuation', sa.String(length=100), nullable=False),
    sa.Column('cash_or_non_cash', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['client_fk'], ['individual_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('macro_s')
    op.drop_table('security')
    op.drop_index('ix_LoanDetails_id', table_name='loandetails')
    op.drop_table('loandetails')
    op.drop_table('macro_ecos')
    op.drop_table('clients')
    op.drop_table('testing')
    op.drop_index('ix_employees_employee_id', table_name='employees')
    op.drop_index('ix_employees_search_name', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('othernames', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('residential_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('postal_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('client_phone_no', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('marital_status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('employer', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('previous_employee_no', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('social_security_no', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('voters_id_no', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('employment_date', sa.DATE(), nullable=True),
    sa.Column('next_of_kin', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('next_of_kin_contact', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('next_of_kin_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('search_name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('employee_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_employees_search_name', 'employees', ['search_name'], unique=False)
    op.create_index('ix_employees_employee_id', 'employees', ['employee_id'], unique=False)
    op.create_table('testing',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('employment_rate', mysql.FLOAT(), nullable=False),
    sa.Column('inflation_rate', mysql.FLOAT(), nullable=False),
    sa.Column('gdp', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('clients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('fname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('middlename', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('lastname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('physical_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('others', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('employment_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('employment_history', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('repayment_approach', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('macro_ecos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('employment_rate', mysql.FLOAT(), nullable=False),
    sa.Column('inflation_rate', mysql.FLOAT(), nullable=False),
    sa.Column('gdp', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('loandetails',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('principal', mysql.FLOAT(), nullable=False),
    sa.Column('annual_interest_rate', mysql.FLOAT(), nullable=False),
    sa.Column('term_years', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('payment_frequency', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_LoanDetails_id', 'loandetails', ['id'], unique=False)
    op.create_table('security',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('collateral_description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('collateral_value', mysql.FLOAT(), nullable=False),
    sa.Column('forced_sale_value', mysql.FLOAT(), nullable=False),
    sa.Column('method_of_valuation', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cash_or_non_cash', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['client_fk'], ['clients.id'], name='security_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('macro_s',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('employment_rate', mysql.FLOAT(), nullable=False),
    sa.Column('inflation_rate', mysql.FLOAT(), nullable=False),
    sa.Column('gdp', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('loan_security')
    op.drop_table('macros')
    op.drop_index(op.f('ix_individual_clients_search_name'), table_name='individual_clients')
    op.drop_index(op.f('ix_individual_clients_employee_id'), table_name='individual_clients')
    op.drop_table('individual_clients')
    # ### end Alembic commands ###
